<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        DB::table('court_varas')->insert([
			['title' => '02ª Vara Federal de Campo Grande', 'court_id' => 3, 'uf' => 'MS'], 
			['title' => '01ª Vara Federal de Campo Grande', 'court_id' => 3, 'uf' => 'MS'], 
			['title' => '02ª Vara Federal de Campo Grande', 'court_id' => 3, 'uf' => 'MS'], 
			['title' => '03ª Vara Federal de Campo Grande', 'court_id' => 3, 'uf' => 'MS'], 
			['title' => '04ª Vara Federal de Campo Grande', 'court_id' => 3, 'uf' => 'MS'], 
			['title' => '05ª Vara Federal de Campo Grande', 'court_id' => 3, 'uf' => 'MS'], 
			['title' => '06ª Vara Federal de Campo Grande', 'court_id' => 3, 'uf' => 'MS'], 
			['title' => '01ª Vara Federal de Campo Grande', 'court_id' => 3, 'uf' => 'MS'], 
			['title' => '01ª Vara Federal de Dourados', 'court_id' => 3, 'uf' => 'MS'], 
			['title' => '02ª Vara Federal de Dourados', 'court_id' => 3, 'uf' => 'MS'], 
			['title' => '01ª Vara Federal de Dourados', 'court_id' => 3, 'uf' => 'MS'], 
			['title' => '01ª Vara Federal de Três Lagoas', 'court_id' => 3, 'uf' => 'MS'], 
			['title' => '01ª Vara Federal de Corumbá', 'court_id' => 3, 'uf' => 'MS'], 
			['title' => '01ª Vara Federal de Ponta Porã', 'court_id' => 3, 'uf' => 'MS'], 
			['title' => '02ª Vara Federal de Ponta Porã', 'court_id' => 3, 'uf' => 'MS'], 
			['title' => '01ª Vara Federal de Naviraí', 'court_id' => 3, 'uf' => 'MS'], 
			['title' => '01ª Vara Federal de Coxim', 'court_id' => 3, 'uf' => 'MS'], 
			['title' => '01ª Vara Federal de São Paulo', 'court_id' => 3, 'uf' => 'SP'], 
			['title' => '02ª Vara Federal de São Paulo', 'court_id' => 3, 'uf' => 'SP'], 
			['title' => '04ª Vara Federal de São Paulo', 'court_id' => 3, 'uf' => 'SP'], 
			['title' => '05ª Vara Federal de São Paulo', 'court_id' => 3, 'uf' => 'SP'], 
			['title' => '06ª Vara Federal de São Paulo', 'court_id' => 3, 'uf' => 'SP'], 
			['title' => '07ª Vara Federal de São Paulo', 'court_id' => 3, 'uf' => 'SP'], 
			['title' => '08ª Vara Federal de São Paulo', 'court_id' => 3, 'uf' => 'SP'], 
			['title' => '09ª Vara Federal de São Paulo', 'court_id' => 3, 'uf' => 'SP'], 
			['title' => '10ª Vara Federal de São Paulo', 'court_id' => 3, 'uf' => 'SP'], 
			['title' => '11ª Vara Federal de São Paulo', 'court_id' => 3, 'uf' => 'SP'], 
			['title' => '12ª Vara Federal de São Paulo', 'court_id' => 3, 'uf' => 'SP'], 
			['title' => '13ª Vara Federal de São Paulo', 'court_id' => 3, 'uf' => 'SP'], 
			['title' => '14ª Vara Federal de São Paulo', 'court_id' => 3, 'uf' => 'SP'], 
			['title' => '17ª Vara Federal de São Paulo', 'court_id' => 3, 'uf' => 'SP'], 
			['title' => '19ª Vara Federal de São Paulo', 'court_id' => 3, 'uf' => 'SP'], 
			['title' => '21ª Vara Federal de São Paulo', 'court_id' => 3, 'uf' => 'SP'], 
			['title' => '22ª Vara Federal de São Paulo', 'court_id' => 3, 'uf' => 'SP'], 
			['title' => '24ª Vara Federal de São Paulo', 'court_id' => 3, 'uf' => 'SP'], 
			['title' => '25ª Vara Federal de São Paulo', 'court_id' => 3, 'uf' => 'SP'], 
			['title' => '26ª Vara Federal de São Paulo', 'court_id' => 3, 'uf' => 'SP'], 
			['title' => '01ª Vara Federal de São Paulo', 'court_id' => 3, 'uf' => 'SP'], 
			['title' => '02ª Vara Federal de São Paulo', 'court_id' => 3, 'uf' => 'SP'], 
			['title' => '03ª Vara Federal de São Paulo', 'court_id' => 3, 'uf' => 'SP'], 
			['title' => '04ª Vara Federal de São Paulo', 'court_id' => 3, 'uf' => 'SP'], 
			['title' => '05ª Vara Federal de São Paulo', 'court_id' => 3, 'uf' => 'SP'], 
			['title' => '06ª Vara Federal de São Paulo', 'court_id' => 3, 'uf' => 'SP'], 
			['title' => '07ª Vara Federal de São Paulo', 'court_id' => 3, 'uf' => 'SP'], 
			['title' => '08ª Vara Federal de São Paulo', 'court_id' => 3, 'uf' => 'SP'], 
			['title' => '09ª Vara Federal de São Paulo', 'court_id' => 3, 'uf' => 'SP'], 
			['title' => '10ª Vara Federal de São Paulo', 'court_id' => 3, 'uf' => 'SP'], 
			['title' => '01ª Vara Federal de São Paulo', 'court_id' => 3, 'uf' => 'SP'], 
			['title' => '02ª Vara Federal de São Paulo', 'court_id' => 3, 'uf' => 'SP'], 
			['title' => '03ª Vara Federal de São Paulo', 'court_id' => 3, 'uf' => 'SP'], 
			['title' => '04ª Vara Federal de São Paulo', 'court_id' => 3, 'uf' => 'SP'], 
			['title' => '05ª Vara Federal de São Paulo', 'court_id' => 3, 'uf' => 'SP'], 
			['title' => '06ª Vara Federal de São Paulo', 'court_id' => 3, 'uf' => 'SP'], 
			['title' => '07ª Vara Federal de São Paulo', 'court_id' => 3, 'uf' => 'SP'], 
			['title' => '08ª Vara Federal de São Paulo', 'court_id' => 3, 'uf' => 'SP'], 
			['title' => '09ª Vara Federal de São Paulo', 'court_id' => 3, 'uf' => 'SP'], 
			['title' => '10ª Vara Federal de São Paulo', 'court_id' => 3, 'uf' => 'SP'], 
			['title' => '01ª Vara Federal de São Paulo ', 'court_id' => 3, 'uf' => 'SP'], 
			['title' => '02ª Vara Federal de São Paulo ', 'court_id' => 3, 'uf' => 'SP'], 
			['title' => '03ª Vara Federal de São Paulo ', 'court_id' => 3, 'uf' => 'SP'], 
			['title' => '04ª Vara Federal de São Paulo ', 'court_id' => 3, 'uf' => 'SP'], 
			['title' => '05ª Vara Federal de São Paulo ', 'court_id' => 3, 'uf' => 'SP'], 
			['title' => '07ª Vara Federal de São Paulo ', 'court_id' => 3, 'uf' => 'SP'], 
			['title' => '08ª Vara Federal de São Paulo ', 'court_id' => 3, 'uf' => 'SP'], 
			['title' => '09ª Vara Federal de São Paulo ', 'court_id' => 3, 'uf' => 'SP'], 
			['title' => '10ª Vara Federal de São Paulo ', 'court_id' => 3, 'uf' => 'SP'], 
			['title' => '12ª Vara Federal de São Paulo ', 'court_id' => 3, 'uf' => 'SP'], 
			['title' => '13ª Vara Federal de São Paulo ', 'court_id' => 3, 'uf' => 'SP'], 
			['title' => '01ª Vara Federal de São Paulo ', 'court_id' => 3, 'uf' => 'SP'], 
			['title' => '02ª Vara Federal de São Paulo ', 'court_id' => 3, 'uf' => 'SP'], 
			['title' => '03ª Vara Federal de São Paulo ', 'court_id' => 3, 'uf' => 'SP'], 
			['title' => '04ª Vara Federal de São Paulo ', 'court_id' => 3, 'uf' => 'SP'], 
			['title' => '05ª Vara Federal de São Paulo ', 'court_id' => 3, 'uf' => 'SP'], 
			['title' => '06ª Vara Federal de São Paulo ', 'court_id' => 3, 'uf' => 'SP'], 
			['title' => '07ª Vara Federal de São Paulo ', 'court_id' => 3, 'uf' => 'SP'], 
			['title' => '08ª Vara Federal de São Paulo ', 'court_id' => 3, 'uf' => 'SP'], 
			['title' => '09ª Vara Federal de São Paulo ', 'court_id' => 3, 'uf' => 'SP'], 
			['title' => '10ª Vara Federal de São Paulo ', 'court_id' => 3, 'uf' => 'SP'], 
			['title' => '11ª Vara Federal de São Paulo ', 'court_id' => 3, 'uf' => 'SP'], 
			['title' => '12ª Vara Federal de São Paulo ', 'court_id' => 3, 'uf' => 'SP'], 
			['title' => '13ª Vara Federal de São Paulo ', 'court_id' => 3, 'uf' => 'SP'], 
			['title' => '14ª Vara Federal de São Paulo ', 'court_id' => 3, 'uf' => 'SP'], 
			['title' => '01ª Vara Federal de São Paulo ', 'court_id' => 3, 'uf' => 'SP'], 
			['title' => '01ª Vara Federal de Ribeirão Preto', 'court_id' => 3, 'uf' => 'SP'], 
			['title' => '02ª Vara Federal de Ribeirão Preto', 'court_id' => 3, 'uf' => 'SP'], 
			['title' => '04ª Vara Federal de Ribeirão Preto', 'court_id' => 3, 'uf' => 'SP'], 
			['title' => '06ª Vara Federal de Ribeirão Preto', 'court_id' => 3, 'uf' => 'SP'], 
			['title' => '07ª Vara Federal de Ribeirão Preto', 'court_id' => 3, 'uf' => 'SP'], 
			['title' => '09ª Vara Federal de Ribeirão Preto', 'court_id' => 3, 'uf' => 'SP'], 
			['title' => '01ª Vara Federal de Ribeirão Preto', 'court_id' => 3, 'uf' => 'SP'], 
			['title' => '02ª Vara Federal de Ribeirão Preto', 'court_id' => 3, 'uf' => 'SP'], 
			['title' => '03ª Vara Federal de Ribeirão Preto', 'court_id' => 3, 'uf' => 'SP'], 
			['title' => '01ª Vara Federal de São José dos Campos', 'court_id' => 3, 'uf' => 'SP'], 
			['title' => '02ª Vara Federal de São José dos Campos', 'court_id' => 3, 'uf' => 'SP'], 
			['title' => '03ª Vara Federal de São José dos Campos', 'court_id' => 3, 'uf' => 'SP'], 
			['title' => '04ª Vara Federal de São José dos Campos', 'court_id' => 3, 'uf' => 'SP'], 
			['title' => '01ª Vara Federal de São José dos Campos', 'court_id' => 3, 'uf' => 'SP'], 
			['title' => '01ª Vara Federal de Santos', 'court_id' => 3, 'uf' => 'SP'], 
			['title' => '02ª Vara Federal de Santos', 'court_id' => 3, 'uf' => 'SP'], 
			['title' => '03ª Vara Federal de Santos', 'court_id' => 3, 'uf' => 'SP'], 
			['title' => '04ª Vara Federal de Santos', 'court_id' => 3, 'uf' => 'SP'], 
			['title' => '05ª Vara Federal de Santos', 'court_id' => 3, 'uf' => 'SP'], 
			['title' => '06ª Vara Federal de Santos', 'court_id' => 3, 'uf' => 'SP'], 
			['title' => '07ª Vara Federal de Santos', 'court_id' => 3, 'uf' => 'SP'], 
			['title' => '01ª Vara Federal de Santos', 'court_id' => 3, 'uf' => 'SP'], 
			['title' => '01ª Vara Federal de Campinas', 'court_id' => 3, 'uf' => 'SP'], 
			['title' => '02ª Vara Federal de Campinas', 'court_id' => 3, 'uf' => 'SP'], 
			['title' => '04ª Vara Federal de Campinas', 'court_id' => 3, 'uf' => 'SP'], 
			['title' => '05ª Vara Federal de Campinas', 'court_id' => 3, 'uf' => 'SP'], 
			['title' => '06ª Vara Federal de Campinas', 'court_id' => 3, 'uf' => 'SP'], 
			['title' => '08ª Vara Federal de Campinas', 'court_id' => 3, 'uf' => 'SP'], 
			['title' => '09ª Vara Federal de Campinas', 'court_id' => 3, 'uf' => 'SP'], 
			['title' => '01ª Vara Federal de Campinas ', 'court_id' => 3, 'uf' => 'SP'], 
			['title' => '02ª Vara Federal de Campinas ', 'court_id' => 3, 'uf' => 'SP'], 
			['title' => '03ª Vara Federal de Campinas ', 'court_id' => 3, 'uf' => 'SP'], 
			['title' => '01ª Vara Federal de São José do Rio Preto', 'court_id' => 3, 'uf' => 'SP'], 
			['title' => '02ª Vara Federal de São José do Rio Preto', 'court_id' => 3, 'uf' => 'SP'], 
			['title' => '04ª Vara Federal de São José do Rio Preto', 'court_id' => 3, 'uf' => 'SP'], 
			['title' => '05ª Vara Federal de São José do Rio Preto', 'court_id' => 3, 'uf' => 'SP'], 
			['title' => '01ª Vara Federal de São José do Rio Preto ', 'court_id' => 3, 'uf' => 'SP'], 
			['title' => '01ª Vara Federal de Araçatuba', 'court_id' => 3, 'uf' => 'SP'], 
			['title' => '02ª Vara Federal de Araçatuba', 'court_id' => 3, 'uf' => 'SP'], 
			['title' => '01ª Vara Federal de Araçatuba ', 'court_id' => 3, 'uf' => 'SP'], 
			['title' => '02ª Vara Federal de Araçatuba ', 'court_id' => 3, 'uf' => 'SP'], 
			['title' => '01ª Vara Federal de Bauru', 'court_id' => 3, 'uf' => 'SP'], 
			['title' => '02ª Vara Federal de Bauru', 'court_id' => 3, 'uf' => 'SP'], 
			['title' => '03ª Vara Federal de Bauru', 'court_id' => 3, 'uf' => 'SP'], 
			['title' => '01ª Vara Federal de Bauru ', 'court_id' => 3, 'uf' => 'SP'], 
			['title' => '01ª Vara Federal de Piracicaba', 'court_id' => 3, 'uf' => 'SP'], 
			['title' => '02ª Vara Federal de Piracicaba', 'court_id' => 3, 'uf' => 'SP'], 
			['title' => '04ª Vara Federal de Piracicaba', 'court_id' => 3, 'uf' => 'SP'], 
			['title' => '01ª Vara Federal de Piracicaba ', 'court_id' => 3, 'uf' => 'SP'], 
			['title' => '02ª Vara Federal de Piracicaba ', 'court_id' => 3, 'uf' => 'SP'], 
			['title' => '01ª Vara Federal de Sorocaba', 'court_id' => 3, 'uf' => 'SP'], 
			['title' => '02ª Vara Federal de Sorocaba', 'court_id' => 3, 'uf' => 'SP'], 
			['title' => '03ª Vara Federal de Sorocaba', 'court_id' => 3, 'uf' => 'SP'], 
			['title' => '04ª Vara Federal de Sorocaba', 'court_id' => 3, 'uf' => 'SP'], 
			['title' => '01ª Vara Federal de Sorocaba ', 'court_id' => 3, 'uf' => 'SP'], 
			['title' => '02ª Vara Federal de Sorocaba ', 'court_id' => 3, 'uf' => 'SP'], 
			['title' => '01ª Vara Federal de Marília', 'court_id' => 3, 'uf' => 'SP'], 
			['title' => '02ª Vara Federal de Marília', 'court_id' => 3, 'uf' => 'SP'], 
			['title' => '03ª Vara Federal de Marília ', 'court_id' => 3, 'uf' => 'SP'], 
			['title' => '01ª Vara Federal de Presidente Prudente', 'court_id' => 3, 'uf' => 'SP'], 
			['title' => '02ª Vara Federal de Presidente Prudente', 'court_id' => 3, 'uf' => 'SP'], 
			['title' => '03ª Vara Federal de Presidente Prudente', 'court_id' => 3, 'uf' => 'SP'], 
			['title' => '01ª Vara Federal de Presidente Prudente ', 'court_id' => 3, 'uf' => 'SP'], 
			['title' => '02ª Vara Federal de Presidente Prudente ', 'court_id' => 3, 'uf' => 'SP'], 
			['title' => '01ª Vara Federal de Franca', 'court_id' => 3, 'uf' => 'SP'], 
			['title' => '02ª Vara Federal de Franca', 'court_id' => 3, 'uf' => 'SP'], 
			['title' => '03ª Vara Federal de Franca', 'court_id' => 3, 'uf' => 'SP'], 
			['title' => '01ª Vara Federal de Franca', 'court_id' => 3, 'uf' => 'SP'], 
			['title' => '01ª Vara Federal de São Bernardo do Campo', 'court_id' => 3, 'uf' => 'SP'], 
			['title' => '02ª Vara Federal de São Bernardo do Campo', 'court_id' => 3, 'uf' => 'SP'], 
			['title' => '03ª Vara Federal de São Bernardo do Campo', 'court_id' => 3, 'uf' => 'SP'], 
			['title' => '01ª Vara Federal de São Bernardo do Campo ', 'court_id' => 3, 'uf' => 'SP'], 
			['title' => '02ª Vara Federal de São Bernardo do Campo ', 'court_id' => 3, 'uf' => 'SP'], 
			['title' => '01ª Vara Federal de São Carlos', 'court_id' => 3, 'uf' => 'SP'], 
			['title' => '02ª Vara Federal de São Carlos', 'court_id' => 3, 'uf' => 'SP'], 
			['title' => '01ª Vara Federal de São Carlos  		', 'court_id' => 3, 'uf' => 'SP'], 
			['title' => '01ª Vara Federal de Assis', 'court_id' => 3, 'uf' => 'SP'], 
			['title' => '01ª Vara Federal de Jaú', 'court_id' => 3, 'uf' => 'SP'], 
			['title' => '01ª Vara Federal de Guaratinguetá', 'court_id' => 3, 'uf' => 'SP'], 
			['title' => '01ª Vara Federal de Guarulhos', 'court_id' => 3, 'uf' => 'SP'], 
			['title' => '02ª Vara Federal de Guarulhos', 'court_id' => 3, 'uf' => 'SP'], 
			['title' => '03ª Vara Federal de Guarulhos', 'court_id' => 3, 'uf' => 'SP'], 
			['title' => '04ª Vara Federal de Guarulhos', 'court_id' => 3, 'uf' => 'SP'], 
			['title' => '05ª Vara Federal de Guarulhos', 'court_id' => 3, 'uf' => 'SP'], 
			['title' => '06ª Vara Federal de Guarulhos', 'court_id' => 3, 'uf' => 'SP'], 
			['title' => '01ª Vara Federal de Guarulhos ', 'court_id' => 3, 'uf' => 'SP'], 
			['title' => '02ª Vara Federal de Guarulhos ', 'court_id' => 3, 'uf' => 'SP'], 
			['title' => '01ª Vara Federal de Araraquara', 'court_id' => 3, 'uf' => 'SP'], 
			['title' => '02ª Vara Federal de Araraquara', 'court_id' => 3, 'uf' => 'SP'], 
			['title' => '01ª Vara Federal de Araraquara  		', 'court_id' => 3, 'uf' => 'SP'], 
			['title' => '01ª Vara Federal de Taubaté', 'court_id' => 3, 'uf' => 'SP'], 
			['title' => '02ª Vara Federal de Taubaté', 'court_id' => 3, 'uf' => 'SP'], 
			['title' => '01ª Vara Federal de Taubaté 			', 'court_id' => 3, 'uf' => 'SP'], 
			['title' => '01ª Vara Federal de Tupã', 'court_id' => 3, 'uf' => 'SP'], 
			['title' => '01ª Vara Federal de Bragança Paulista', 'court_id' => 3, 'uf' => 'SP'], 
			['title' => '01ª Vara Federal de Bragança Paulista 	', 'court_id' => 3, 'uf' => 'SP'], 
			['title' => '01ª Vara Federal de Jales', 'court_id' => 3, 'uf' => 'SP'], 
			['title' => '01ª Vara Federal de Ourinhos', 'court_id' => 3, 'uf' => 'SP'], 
			['title' => '01ª Vara Federal de Ourinhos  			', 'court_id' => 3, 'uf' => 'SP'], 
			['title' => '01ª Vara Federal de Santo André', 'court_id' => 3, 'uf' => 'SP'], 
			['title' => '02ª Vara Federal de Santo André', 'court_id' => 3, 'uf' => 'SP'], 
			['title' => '03ª Vara Federal de Santo André', 'court_id' => 3, 'uf' => 'SP'], 
			['title' => '01ª Vara Federal de Santo André', 'court_id' => 3, 'uf' => 'SP'], 
			['title' => '01ª Vara Federal de São João da Boa Vista', 'court_id' => 3, 'uf' => 'SP'], 
			['title' => '02ª Vara Federal de Jundiaí', 'court_id' => 3, 'uf' => 'SP'], 
			['title' => '01ª Vara Federal de Jundiaí', 'court_id' => 3, 'uf' => 'SP'], 
			['title' => '02ª Vara Federal de Jundiaí', 'court_id' => 3, 'uf' => 'SP'], 
			['title' => '01ª Vara Federal de Registro', 'court_id' => 3, 'uf' => 'SP'], 
			['title' => '01ª Vara Federal de Osasco', 'court_id' => 3, 'uf' => 'SP'], 
			['title' => '02ª Vara Federal de Osasco', 'court_id' => 3, 'uf' => 'SP'], 
			['title' => '01ª Vara Federal de Osasco', 'court_id' => 3, 'uf' => 'SP'], 
			['title' => '02ª Vara Federal de Osasco', 'court_id' => 3, 'uf' => 'SP'], 
			['title' => '01ª Vara Federal de Botucatu', 'court_id' => 3, 'uf' => 'SP'], 
			['title' => '01ª Vara Federal de Botucatu ', 'court_id' => 3, 'uf' => 'SP'], 
			['title' => '01ª Vara Federal de Avaré', 'court_id' => 3, 'uf' => 'SP'], 
			['title' => '02ª Vara Federal de Mogi das Cruzes', 'court_id' => 3, 'uf' => 'SP'], 
			['title' => '01ª Vara Federal de Mogi das Cruzes', 'court_id' => 3, 'uf' => 'SP'], 
			['title' => '02ª Vara Federal de Mogi das Cruzes', 'court_id' => 3, 'uf' => 'SP'], 
			['title' => '01ª Vara Federal de Americana', 'court_id' => 3, 'uf' => 'SP'], 
			['title' => '01ª Vara Federal de Americana', 'court_id' => 3, 'uf' => 'SP'], 
			['title' => '01ª Vara Federal de Caraguatatuba', 'court_id' => 3, 'uf' => 'SP'], 
			['title' => '01ª Vara Federal de Catanduva', 'court_id' => 3, 'uf' => 'SP'], 
			['title' => '01ª Vara Federal de Andradina', 'court_id' => 3, 'uf' => 'SP'], 
			['title' => '01ª Vara Federal de Barretos', 'court_id' => 3, 'uf' => 'SP'], 
			['title' => '01ª Vara Federal de Itapeva', 'court_id' => 3, 'uf' => 'SP'], 
			['title' => '01ª Vara Federal de Mauá', 'court_id' => 3, 'uf' => 'SP'], 
			['title' => '01ª Vara Federal de Mauá', 'court_id' => 3, 'uf' => 'SP'], 
			['title' => '01ª Vara Federal de São Vicente', 'court_id' => 3, 'uf' => 'SP'], 
			['title' => '01ª Vara Federal de São Vicente ', 'court_id' => 3, 'uf' => 'SP'], 
			['title' => '01ª Vara Federal de Lins', 'court_id' => 3, 'uf' => 'SP'], 
			['title' => '02ª Vara Federal de Limeira', 'court_id' => 3, 'uf' => 'SP'], 
			['title' => '01ª Vara Federal de Limeira', 'court_id' => 3, 'uf' => 'SP'], 
			['title' => '02ª Vara Federal de Barueri', 'court_id' => 3, 'uf' => 'SP'], 
			['title' => '01ª Vara Federal de Barueri', 'court_id' => 3, 'uf' => 'SP'], 
			['title' => '01ª Vara Federal de Barueri', 'court_id' => 3, 'uf' => 'SP'] 			
   
        ]);
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        //
    }
};
