<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        DB::table('court_varas')->insert([
			['title' => 'CEJUSCON da Seção Judiciária do Paraná', 'court_id' => 4, 'uf' => 'PR'], 
            ['title' => '1ª Vara Federal de Curitiba	', 'court_id' => 4, 'uf' => 'PR'], 
			['title' => '2ª Vara Federal de Curitiba', 'court_id' => 4, 'uf' => 'PR'], 
			['title' => '3ª Vara Federal de Curitiba', 'court_id' => 4, 'uf' => 'PR'], 
			['title' => '4ª Vara Federal de Curitiba', 'court_id' => 4, 'uf' => 'PR'], 
			['title' => '5ª Vara Federal de Curitiba', 'court_id' => 4, 'uf' => 'PR'], 
			['title' => '6ª Vara Federal de Curitiba', 'court_id' => 4, 'uf' => 'PR'], 
			['title' => '7ª Vara Federal de Curitiba', 'court_id' => 4, 'uf' => 'PR'], 
			['title' => '8ª Vara Federal de Curitiba', 'court_id' => 4, 'uf' => 'PR'], 
			['title' => '9ª Vara Federal de Curitiba', 'court_id' => 4, 'uf' => 'PR'], 
			['title' => '10ª Vara Federal de Curitiba', 'court_id' => 4, 'uf' => 'PR'], 
			['title' => '11ª Vara Federal de Curitiba', 'court_id' => 4, 'uf' => 'PR'], 
			['title' => '12ª Vara Federal de Curitiba', 'court_id' => 4, 'uf' => 'PR'], 
			['title' => '13ª Vara Federal de Curitiba', 'court_id' => 4, 'uf' => 'PR'], 
			['title' => '14ª Vara Federal de Curitiba', 'court_id' => 4, 'uf' => 'PR'], 
			['title' => '15ª Vara Federal de Curitiba', 'court_id' => 4, 'uf' => 'PR'], 
			['title' => '16ª Vara Federal de Curitiba', 'court_id' => 4, 'uf' => 'PR'], 
			['title' => '17ª Vara Federal de Curitiba', 'court_id' => 4, 'uf' => 'PR'], 
			['title' => '18ª Vara Federal de Curitiba', 'court_id' => 4, 'uf' => 'PR'], 
			['title' => '19ª Vara Federal de Curitiba', 'court_id' => 4, 'uf' => 'PR'], 
			['title' => '20ª Vara Federal de Curitiba', 'court_id' => 4, 'uf' => 'PR'], 
			['title' => '21ª Vara Federal de Curitiba', 'court_id' => 4, 'uf' => 'PR'], 
			['title' => '22ª Vara Federal de Curitiba', 'court_id' => 4, 'uf' => 'PR'], 
			['title' => '23ª Vara Federal de Curitiba', 'court_id' => 4, 'uf' => 'PR'], 
			['title' => 'DIVISÃO DE CONCILIAÇÕES', 'court_id' => 4, 'uf' => 'PR'], 
			['title' => '3° Núcleo de Justiça 4.0 - PR	', 'court_id' => 4, 'uf' => 'PR'], 
			['title' => '1ª Turma Recursal do Paraná	', 'court_id' => 4, 'uf' => 'PR'], 
			['title' => '2ª Turma Recursal do Paraná	', 'court_id' => 4, 'uf' => 'PR'], 
			['title' => '3ª Turma Recursal do Paraná	', 'court_id' => 4, 'uf' => 'PR'], 
			['title' => '4ª Turma Recursal do Paraná	', 'court_id' => 4, 'uf' => 'PR'], 
			['title' => '1ª Unidade de Apoio de Curitiba', 'court_id' => 4, 'uf' => 'PR'], 
			['title' => '1ª Vara Federal de Jacarezinho', 'court_id' => 4, 'uf' => 'PR'], 
			['title' => '1ª UAA em Ibaiti', 'court_id' => 4, 'uf' => 'PR'], 
			['title' => '1ª UAA em Wenceslau Braz', 'court_id' => 4, 'uf' => 'PR'], 
			['title' => '1ª Vara Federal de Apucarana', 'court_id' => 4, 'uf' => 'PR'], 
			['title' => '1ª Vara Federal de Campo Mourão', 'court_id' => 4, 'uf' => 'PR'], 
			['title' => '2ª Vara Federal de Campo Mourão', 'court_id' => 4, 'uf' => 'PR'], 
			['title' => 'CEJUSCON-CAMPO MOURÃO', 'court_id' => 4, 'uf' => 'PR'], 		
			['title' => '1ª Vara Federal de Cascavel', 'court_id' => 4, 'uf' => 'PR'], 
			['title' => '2ª Vara Federal de Cascavel', 'court_id' => 4, 'uf' => 'PR'], 
			['title' => '3ª Vara Federal de Cascavel', 'court_id' => 4, 'uf' => 'PR'],
			['title' => '4ª Vara Federal de Cascavel	', 'court_id' => 4, 'uf' => 'PR'], 
			['title' => 'CEJUSCON-CASCAVEL	', 'court_id' => 4, 'uf' => 'PR'], 			
			['title' => '1ª Vara Federal de Foz do Iguaçu', 'court_id' => 4, 'uf' => 'PR'], 
			['title' => '2ª Vara Federal de Foz do Iguaçu', 'court_id' => 4, 'uf' => 'PR'], 
			['title' => '3ª Vara Federal de Foz do Iguaçu', 'court_id' => 4, 'uf' => 'PR'], 
			['title' => '4ª Vara Federal de Foz do Iguaçu', 'court_id' => 4, 'uf' => 'PR'], 
			['title' => '5ª Vara Federal de Foz do Iguaçu	', 'court_id' => 4, 'uf' => 'PR'], 
			['title' => '6ª Vara Federal de Foz do Iguaçu	', 'court_id' => 4, 'uf' => 'PR'], 
			['title' => 'CEJUSCON-FOZ DO IGUAÇU', 'court_id' => 4, 'uf' => 'PR'], 
			['title' => '1ª Vara Federal de Francisco Beltrão', 'court_id' => 4, 'uf' => 'PR'], 
			['title' => '2ª Vara Federal de Francisco Beltrão', 'court_id' => 4, 'uf' => 'PR'], 
			['title' => 'CEJUSCON-FRANCISCO BELTRÃO', 'court_id' => 4, 'uf' => 'PR'], 
			['title' => '1ª Vara Federal de Guaíra', 'court_id' => 4, 'uf' => 'PR'], 
			['title' => '1ª Vara Federal de Guarapuava', 'court_id' => 4, 'uf' => 'PR'], 
			['title' => '2ª Vara Federal de Guarapuava', 'court_id' => 4, 'uf' => 'PR'],			
			['title' => 'CEJUSCON-GUARAPUAVA', 'court_id' => 4, 'uf' => 'PR'], 
			['title' => '1ª Vara Federal de Jacarezinho', 'court_id' => 4, 'uf' => 'PR'], 
			['title' => '1ª UAA em Ibaiti', 'court_id' => 4, 'uf' => 'PR'], 
			['title' => '1ª UAA em Wenceslau Braz', 'court_id' => 4, 'uf' => 'PR'], 			
			['title' => '1ª Vara Federal de Londrina', 'court_id' => 4, 'uf' => 'PR'], 
			['title' => '2ª Vara Federal de Londrina', 'court_id' => 4, 'uf' => 'PR'], 
			['title' => '3ª Vara Federal de Londrina', 'court_id' => 4, 'uf' => 'PR'], 
			['title' => '4ª Vara Federal de Londrina', 'court_id' => 4, 'uf' => 'PR'], 
			['title' => '5ª Vara Federal de Londrina', 'court_id' => 4, 'uf' => 'PR'], 
			['title' => '6ª Vara Federal de Londrina', 'court_id' => 4, 'uf' => 'PR'], 
			['title' => '7ª Vara Federal de Londrina', 'court_id' => 4, 'uf' => 'PR'], 
			['title' => '8ª Vara Federal de Londrina', 'court_id' => 4, 'uf' => 'PR'], 
			['title' => 'CEJUSCON-LONDRINA', 'court_id' => 4, 'uf' => 'PR'], 
			['title' => '1ª UAA em Arapongas', 'court_id' => 4, 'uf' => 'PR'], 
			['title' => '2ª UAA em Arapongas', 'court_id' => 4, 'uf' => 'PR'], 
			['title' => '4ª UAA em Arapongas', 'court_id' => 4, 'uf' => 'PR'], 
			['title' => '5ª UAA em Arapongas', 'court_id' => 4, 'uf' => 'PR'], 
			['title' => '6ª UAA em Arapongas', 'court_id' => 4, 'uf' => 'PR'], 
			['title' => '7ª UAA em Arapongas', 'court_id' => 4, 'uf' => 'PR'], 
			['title' => '1ª UAA em Astorga', 'court_id' => 4, 'uf' => 'PR'], 
			['title' => '2ª UAA em Astorga', 'court_id' => 4, 'uf' => 'PR'], 
			['title' => '3ª UAA em Astorga', 'court_id' => 4, 'uf' => 'PR'], 
			['title' => '4ª UAA em Astorga', 'court_id' => 4, 'uf' => 'PR'], 
			['title' => '5ª UAA em Astorga', 'court_id' => 4, 'uf' => 'PR'], 
			['title' => '6ª UAA em Astorga', 'court_id' => 4, 'uf' => 'PR'], 
			['title' => '7ª UAA em Astorga', 'court_id' => 4, 'uf' => 'PR'], 
			['title' => '13ª UAA em Astorga', 'court_id' => 4, 'uf' => 'PR'], 
			['title' => '2ª UAA em Ibaiti', 'court_id' => 4, 'uf' => 'PR'], 
			['title' => '3ª UAA em Ibaiti', 'court_id' => 4, 'uf' => 'PR'], 
			['title' => '4ª UAA em Ibaiti', 'court_id' => 4, 'uf' => 'PR'],
			['title' => '5ª UAA em Ibaiti', 'court_id' => 4, 'uf' => 'PR'], 
			['title' => '6ª UAA em Ibaiti', 'court_id' => 4, 'uf' => 'PR'], 
			['title' => '7ª UAA em Ibaiti', 'court_id' => 4, 'uf' => 'PR'], 
			['title' => '8ª UAA em Ibaiti', 'court_id' => 4, 'uf' => 'PR'], 
			['title' => '9ª UAA em Ibaiti', 'court_id' => 4, 'uf' => 'PR'], 
			['title' => '2ª UAA em Ivaiporã', 'court_id' => 4, 'uf' => 'PR'], 
			['title' => '7ª UAA em Wenceslau Braz', 'court_id' => 4, 'uf' => 'PR'], 
			['title' => '8ª UAA em Wenceslau Braz', 'court_id' => 4, 'uf' => 'PR'],			
			['title' => '1ª Vara Federal de Maringá', 'court_id' => 4, 'uf' => 'PR'], 
			['title' => '2ª Vara Federal de Maringá', 'court_id' => 4, 'uf' => 'PR'], 
			['title' => '3ª Vara Federal de Maringá', 'court_id' => 4, 'uf' => 'PR'], 
			['title' => '4ª Vara Federal de Maringá', 'court_id' => 4, 'uf' => 'PR'], 
			['title' => '5ª Vara Federal de Maringá', 'court_id' => 4, 'uf' => 'PR'], 
			['title' => '6ª Vara Federal de Maringá', 'court_id' => 4, 'uf' => 'PR'], 
			['title' => 'CEJUSCON-MARINGÁ', 'court_id' => 4, 'uf' => 'PR'], 
			['title' => '8ª UAA em Astorga', 'court_id' => 4, 'uf' => 'PR'], 
			['title' => '9ª UAA em Astorga', 'court_id' => 4, 'uf' => 'PR'], 
			['title' => '10ª UAA em Astorga	', 'court_id' => 4, 'uf' => 'PR'], 
			['title' => '11ª UAA em Astorga	', 'court_id' => 4, 'uf' => 'PR'], 
			['title' => '12ª UAA em Astorga	', 'court_id' => 4, 'uf' => 'PR'], 
			['title' => '13ª UAA em Astorga	', 'court_id' => 4, 'uf' => 'PR'], 			
			['title' => '1ª Vara Federal de Paranaguá', 'court_id' => 4, 'uf' => 'PR'], 			
			['title' => '1ª Vara Federal de Paranavaí', 'court_id' => 4, 'uf' => 'PR'], 			
			['title' => '1ª Vara Federal de Pato Branco', 'court_id' => 4, 'uf' => 'PR'], 			
			['title' => '1ª Vara Federal de Pitanga', 'court_id' => 4, 'uf' => 'PR'], 			
			['title' => '1ª Vara Federal de Ponta Grossa', 'court_id' => 4, 'uf' => 'PR'], 			
			['title' => '2ª Vara Federal de Ponta Grossa', 'court_id' => 4, 'uf' => 'PR'], 			
			['title' => '3ª Vara Federal de Ponta Grossa', 'court_id' => 4, 'uf' => 'PR'], 			
			['title' => '4ª Vara Federal de Ponta Grossa', 'court_id' => 4, 'uf' => 'PR'], 			
			['title' => '5ª Vara Federal de Ponta Grossa', 'court_id' => 4, 'uf' => 'PR'], 			
			['title' => 'CEJUSCON-PONTA GROSSA	', 'court_id' => 4, 'uf' => 'PR'], 			
			['title' => '10ª UAA em Ibaiti', 'court_id' => 4, 'uf' => 'PR'], 			
			['title' => '11ª UAA em Ibaiti', 'court_id' => 4, 'uf' => 'PR'], 			
			['title' => '12ª UAA em Ibaiti', 'court_id' => 4, 'uf' => 'PR'], 			
			['title' => '12ª UAA em Ibaiti', 'court_id' => 4, 'uf' => 'PR'], 			
			['title' => '13ª UAA em Ibaiti	', 'court_id' => 4, 'uf' => 'PR'], 			
			['title' => '3ª UAA em Wenceslau Braz', 'court_id' => 4, 'uf' => 'PR'], 			
			['title' => '4ª UAA em Wenceslau Braz', 'court_id' => 4, 'uf' => 'PR'], 			
			['title' => '1ª Vara Federal de Telêmaco Borba', 'court_id' => 4, 'uf' => 'PR'], 			
			['title' => '14ª UAA de Ibaiti', 'court_id' => 4, 'uf' => 'PR'], 	
			
			['title' => '1ª Vara Federal de Toledo', 'court_id' => 4, 'uf' => 'PR'], 			
			['title' => '1ª Vara Federal de Umuarama', 'court_id' => 4, 'uf' => 'PR'], 			
			['title' => '2ª Vara Federal de Umuarama', 'court_id' => 4, 'uf' => 'PR'], 			
			['title' => '3ª Vara Federal de Umuarama', 'court_id' => 4, 'uf' => 'PR'], 			
			['title' => 'CEJUSCON-UMUARAMA', 'court_id' => 4, 'uf' => 'PR'], 			
			['title' => '1ª Vara Federal de União da Vitória', 'court_id' => 4, 'uf' => 'PR'], 
			
			['title' => '1ª Vara Federal de Blumenau', 'court_id' => 4, 'uf' => 'SC'],
			['title' => '2ª Vara Federal de Blumenau', 'court_id' => 4, 'uf' => 'SC'], 			
			['title' => '3ª Vara Federal de Blumenau', 'court_id' => 4, 'uf' => 'SC'], 			
			['title' => '4ª Vara Federal de Blumenau', 'court_id' => 4, 'uf' => 'SC'], 			
			['title' => '5ª Vara Federal de Blumenau	', 'court_id' => 4, 'uf' => 'SC'], 			
			['title' => 'CEJUSCON-BLUMENAU', 'court_id' => 4, 'uf' => 'SC'], 			
			['title' => 'Unidade de Auxílio em Blumenau', 'court_id' => 4, 'uf' => 'SC'], 			
			['title' => '1ª Vara Federal de Brusque', 'court_id' => 4, 'uf' => 'SC'], 			
			['title' => '1ª Vara Federal de Caçador', 'court_id' => 4, 'uf' => 'SC'], 			
			['title' => '1ª Vara Federal de Chapecó', 'court_id' => 4, 'uf' => 'SC'], 			
			['title' => '2ª Vara Federal de Chapecó', 'court_id' => 4, 'uf' => 'SC'], 			
			['title' => '3ª Vara Federal de Chapecó', 'court_id' => 4, 'uf' => 'SC'],  			
			['title' => 'CEJUSCON-CHAPECÓ', 'court_id' => 4, 'uf' => 'SC'], 			
			['title' => '1ª Vara Federal de Concórdia', 'court_id' => 4, 'uf' => 'SC'], 			
			['title' => '1ª Vara Federal de Criciúma', 'court_id' => 4, 'uf' => 'SC'], 			
			['title' => '2ª Vara Federal de Criciúma', 'court_id' => 4, 'uf' => 'SC'], 			
			['title' => '3ª Vara Federal de Criciúma', 'court_id' => 4, 'uf' => 'SC'], 			
			['title' => '4ª Vara Federal de Criciúma', 'court_id' => 4, 'uf' => 'SC'], 			
			['title' => 'CEJUSCON-CRICIÚMA', 'court_id' => 4, 'uf' => 'SC'], 			
			['title' => 'CEJUSCON da Seção Judiciária de Santa Catarina', 'court_id' => 4, 'uf' => 'SC'], 			
			['title' => '1ª Vara Federal de Florianópolis', 'court_id' => 4, 'uf' => 'SC'], 			
			['title' => '2ª Vara Federal de Florianópolis', 'court_id' => 4, 'uf' => 'SC'], 			
			['title' => '3ª Vara Federal de Florianópolis', 'court_id' => 4, 'uf' => 'SC'], 			
			['title' => '4ª Vara Federal de Florianópolis', 'court_id' => 4, 'uf' => 'SC'], 			
			['title' => '5ª Vara Federal de Florianópolis', 'court_id' => 4, 'uf' => 'SC'], 			
			['title' => '6ª Vara Federal de Florianópolis', 'court_id' => 4, 'uf' => 'SC'], 			
			['title' => '7ª Vara Federal de Florianópolis', 'court_id' => 4, 'uf' => 'SC'], 			
			['title' => '8ª Vara Federal de Florianópolis', 'court_id' => 4, 'uf' => 'SC'], 			
			['title' => '9ª Vara Federal de Florianópolis', 'court_id' => 4, 'uf' => 'SC'], 			
			['title' => 'CEJUSCON-FLORIANÓPOLIS', 'court_id' => 4, 'uf' => 'SC'],		 			
			['title' => '2° Núcleo de Justiça 4.0 - SC', 'court_id' => 4, 'uf' => 'SC'],	 			
			['title' => '3° Núcleo de Justiça 4.0 - SC', 'court_id' => 4, 'uf' => 'SC'],	 			
			['title' => '1ª Turma Recursal de Santa Catarina', 'court_id' => 4, 'uf' => 'SC'],	 			
			['title' => '2ª Turma Recursal de Santa Catarina', 'court_id' => 4, 'uf' => 'SC'],	 			
			['title' => '3ª Turma Recursal de Santa Catarina', 'court_id' => 4, 'uf' => 'SC'],	 			
			['title' => '1ª Unidade de Apoio em Execução Fiscal (PRCTB15)', 'court_id' => 4, 'uf' => 'SC'],	 			
			['title' => '2ª Unidade de Apoio em Execução Fiscal (PRCTB16)', 'court_id' => 4, 'uf' => 'SC'],	 			
			['title' => '3ª Unidade de Apoio em Execução Fiscal (PRCTB19)', 'court_id' => 4, 'uf' => 'SC'],	 			
			['title' => '4ª Unidade de Apoio em Execução Fiscal (PRLON07)', 'court_id' => 4, 'uf' => 'SC'],	 			
			['title' => '5ª Unidade de Apoio em Execução Fiscal (PRMAR05)', 'court_id' => 4, 'uf' => 'SC'],	 			
			['title' => '6ª Unidade de Apoio em Execução Fiscal (PRPGO03)', 'court_id' => 4, 'uf' => 'SC'],	 			
			['title' => '7ª Unidade de Apoio em Execução Fiscal (RSPOA16)', 'court_id' => 4, 'uf' => 'SC'],	 			
			['title' => '8ª Unidade de Apoio em Execução Fiscal (RSPOA19)', 'court_id' => 4, 'uf' => 'SC'],	 			
			['title' => '9ª Unidade de Apoio em Execução Fiscal (RSPOA23)	', 'court_id' => 4, 'uf' => 'SC'],	 			
			['title' => '10ª Unidade de Apoio em Execução Fiscal (RSCAX04)	', 'court_id' => 4, 'uf' => 'SC'],	 			
			['title' => '11ª Unidade de Apoio em Execução Fiscal (RSPFU01)', 'court_id' => 4, 'uf' => 'SC'],			 			
			['title' => '12ª Unidade de Apoio em Execução Fiscal (RSPEL01)', 'court_id' => 4, 'uf' => 'SC'],			 			
			['title' => '13ª Unidade de Apoio em Execução Fiscal (RSSMA04)', 'court_id' => 4, 'uf' => 'SC'],			 			
			['title' => '14ª Unidade de Apoio em Execução Fiscal (RSSAN03)', 'court_id' => 4, 'uf' => 'SC'],			 			
			['title' => '1ª Vara Federal de Itajaí', 'court_id' => 4, 'uf' => 'SC'],			 			
			['title' => '2ª Vara Federal de Itajaí', 'court_id' => 4, 'uf' => 'SC'],			 			
			['title' => '3ª Vara Federal de Itajaí	', 'court_id' => 4, 'uf' => 'SC'],			 			
			['title' => '4ª Vara Federal de Itajaí	', 'court_id' => 4, 'uf' => 'SC'],			 			
			['title' => 'CEJUSCON-ITAJAÍ', 'court_id' => 4, 'uf' => 'SC'],					 			
			['title' => '1ª Vara Federal de Jaraguá do Sul', 'court_id' => 4, 'uf' => 'SC'],			 			
			['title' => 'CEJUSCON-JARAGUÁ DO SUL', 'court_id' => 4, 'uf' => 'SC'],			 			
			['title' => '1ª Vara Federal de Joaçaba', 'court_id' => 4, 'uf' => 'SC'],			 			
			['title' => '1ª Vara Federal de Joinville', 'court_id' => 4, 'uf' => 'SC'],			 			
			['title' => '2ª Vara Federal de Joinville', 'court_id' => 4, 'uf' => 'SC'],			 			
			['title' => '3ª Vara Federal de Joinville', 'court_id' => 4, 'uf' => 'SC'],			 			
			['title' => '4ª Vara Federal de Joinville', 'court_id' => 4, 'uf' => 'SC'],			 			
			['title' => '5ª Vara Federal de Joinville', 'court_id' => 4, 'uf' => 'SC'],			 			
			['title' => '6ª Vara Federal de Joinville', 'court_id' => 4, 'uf' => 'SC'],			 			
			['title' => 'CEJUSCON-JOINVILLE', 'court_id' => 4, 'uf' => 'SC'],			 			
			['title' => '1ª Vara Federal de Lages', 'court_id' => 4, 'uf' => 'SC'],			 			
			['title' => '2ª Vara Federal de Lages', 'court_id' => 4, 'uf' => 'SC'],			 			
			['title' => 'CEJUSCON-LAGES', 'court_id' => 4, 'uf' => 'SC'],			 			
			['title' => '1ª Vara Federal de Laguna', 'court_id' => 4, 'uf' => 'SC'],			 			
			['title' => '1ª Vara Federal de Mafra', 'court_id' => 4, 'uf' => 'SC'],			 			
			['title' => '1ª Vara Federal de Rio do Sul', 'court_id' => 4, 'uf' => 'SC'],			 			
			['title' => '1ª Vara Federal de São Miguel do Oeste', 'court_id' => 4, 'uf' => 'SC'],			 			
			['title' => '1ª Vara Federal de Tubarão', 'court_id' => 4, 'uf' => 'SC'],			 			
			['title' => '2ª Vara Federal de Tubarão', 'court_id' => 4, 'uf' => 'SC'],			 			
			['title' => 'CEJUSCON-TUBARÃO', 'court_id' => 4, 'uf' => 'SC'],			 			
			['title' => '1ª Vara Federal de Bento Gonçalves', 'court_id' => 4, 'uf' => 'RS'],			 			
			['title' => '2ª Vara Federal de Bento Gonçalves', 'court_id' => 4, 'uf' => 'RS'],			 			
			['title' => 'CEJUSCON-BENTO GONÇALVES', 'court_id' => 4, 'uf' => 'RS'],			 			
			['title' => '2ª UAA em Nova Prata', 'court_id' => 4, 'uf' => 'RS'],			 			
			['title' => '1ª Vara Federal de Cachoeira do Sul', 'court_id' => 4, 'uf' => 'RS'],			 			
			['title' => '1ª Vara Federal de Canoas', 'court_id' => 4, 'uf' => 'RS'],			 			
			['title' => '2ª Vara Federal de Canoas', 'court_id' => 4, 'uf' => 'RS'],			 			
			['title' => '3ª Vara Federal de Canoas', 'court_id' => 4, 'uf' => 'RS'],			 			
			['title' => 'CEJUSCON-CANOAS', 'court_id' => 4, 'uf' => 'RS'],			 			
			['title' => '1ª Vara Federal de Capão da Canoa', 'court_id' => 4, 'uf' => 'RS'],			 			
			['title' => '2ª UAA em Torres', 'court_id' => 4, 'uf' => 'RS'],			 			
			['title' => '1ª Vara Federal de Carazinho', 'court_id' => 4, 'uf' => 'RS'],			 			
			['title' => '2ª Vara Federal de Carazinho', 'court_id' => 4, 'uf' => 'RS'],			 			
			['title' => 'CEJUSCON-CARAZINHO', 'court_id' => 4, 'uf' => 'RS'],			 			
			['title' => '2ª UAA em Soledade', 'court_id' => 4, 'uf' => 'RS'],			 			
			['title' => '1ª Vara Federal de Caxias do Sul', 'court_id' => 4, 'uf' => 'RS'],			 			
			['title' => '2ª Vara Federal de Caxias do Sul', 'court_id' => 4, 'uf' => 'RS'],			 			
			['title' => '3ª Vara Federal de Caxias do Sul', 'court_id' => 4, 'uf' => 'RS'],			 			
			['title' => '4ª Vara Federal de Caxias do Sul', 'court_id' => 4, 'uf' => 'RS'],			 			
			['title' => '5ª Vara Federal de Caxias do Sul', 'court_id' => 4, 'uf' => 'RS'],			 			
			['title' => 'CEJUSCON-CAXIAS', 'court_id' => 4, 'uf' => 'RS'],			 			
			['title' => '1ª UAA Integrada em Gramado e Canela', 'court_id' => 4, 'uf' => 'RS'],			 			
			['title' => '2ª UAA Integrada em Gramado e Canela', 'court_id' => 4, 'uf' => 'RS'],			 			
			['title' => '4ª UAA Integrada em Gramado e Canela', 'court_id' => 4, 'uf' => 'RS'],			 			
			['title' => '3ª UAA em Nova Prata', 'court_id' => 4, 'uf' => 'RS'],		 			
			['title' => '1ª UAA em Vacaria', 'court_id' => 4, 'uf' => 'RS'],		 			
			['title' => '3ª UAA em Vacaria', 'court_id' => 4, 'uf' => 'RS'],		 			
			['title' => '4ª UAA em Vacaria', 'court_id' => 4, 'uf' => 'RS'],		 			
			['title' => '5ª UAA em Vacaria', 'court_id' => 4, 'uf' => 'RS'],		 			
			['title' => '1ª Vara Federal de Cruz Alta', 'court_id' => 4, 'uf' => 'RS'],		 			
			['title' => '1ª Vara Federal de Erechim', 'court_id' => 4, 'uf' => 'RS'],		 			
			['title' => '2ª Vara Federal de Erechim', 'court_id' => 4, 'uf' => 'RS'],		 			
			['title' => 'CEJUSCON-ERECHIM', 'court_id' => 4, 'uf' => 'RS'],		 			
			['title' => '1ª Vara Federal de Gravataí', 'court_id' => 4, 'uf' => 'RS'],		 			
			['title' => '2ª Vara Federal de Gravataí', 'court_id' => 4, 'uf' => 'RS'],		 			
			['title' => '3ª Vara Federal de Gravataí', 'court_id' => 4, 'uf' => 'RS'],		 			
			['title' => '1ª Vara Federal de Ijuí', 'court_id' => 4, 'uf' => 'RS'],		 			
			['title' => '1ª Vara Federal de Lajeado', 'court_id' => 4, 'uf' => 'RS'],		 			
			['title' => '2ª Vara Federal de Lajeado', 'court_id' => 4, 'uf' => 'RS'],		 			
			['title' => 'CEJUSCON - LAJEADO', 'court_id' => 4, 'uf' => 'RS'],		 			
			['title' => '1ª Vara Federal de Novo Hamburgo', 'court_id' => 4, 'uf' => 'RS'],		 			
			['title' => '2ª Vara Federal de Novo Hamburgo', 'court_id' => 4, 'uf' => 'RS'],		 			
			['title' => '3ª Vara Federal de Novo Hamburgo', 'court_id' => 4, 'uf' => 'RS'],		 			
			['title' => '4ª Vara Federal de Novo Hamburgo', 'court_id' => 4, 'uf' => 'RS'],		 			
			['title' => '5ª Vara Federal de Novo Hamburgo', 'court_id' => 4, 'uf' => 'RS'],		 			
			['title' => '6ª Vara Federal de Novo Hamburgo', 'court_id' => 4, 'uf' => 'RS'],		 			
			['title' => 'CEJUSCON-NOVO HAMBURGO', 'court_id' => 4, 'uf' => 'RS'],		 			
			['title' => '8ª UAA Integrada em Gramado e Canela', 'court_id' => 4, 'uf' => 'RS'],		 			
			['title' => '1ª UAA em São Leopoldo', 'court_id' => 4, 'uf' => 'RS'],		 			
			['title' => '3ª UAA em São Leopoldo', 'court_id' => 4, 'uf' => 'RS'],		 			
			['title' => '4ª UAA em São Leopoldo', 'court_id' => 4, 'uf' => 'RS'],		 			
			['title' => '1ª Vara Federal de Palmeira das Missões', 'court_id' => 4, 'uf' => 'RS'],		 			
			['title' => '1ª UAA em Frederico Westphalen', 'court_id' => 4, 'uf' => 'RS'],		 			
			['title' => '1ª Vara Federal de Passo Fundo', 'court_id' => 4, 'uf' => 'RS'],		 			
			['title' => '2ª Vara Federal de Passo Fundo', 'court_id' => 4, 'uf' => 'RS'],		 			
			['title' => '3ª Vara Federal de Passo Fundo', 'court_id' => 4, 'uf' => 'RS'],		 			
			['title' => '4ª Vara Federal de Passo Fundo', 'court_id' => 4, 'uf' => 'RS'],		 			
			['title' => '3ª UAA em Soledade', 'court_id' => 4, 'uf' => 'RS'],			 			
			['title' => '2ª Vara Federal de Pelotas', 'court_id' => 4, 'uf' => 'RS'],			 			
			['title' => '3ª Vara Federal de Pelotas', 'court_id' => 4, 'uf' => 'RS'],			 			
			['title' => 'CEJUSCON-PELOTAS', 'court_id' => 4, 'uf' => 'RS'],			 			
			['title' => '1ª UAA em Jaguarão', 'court_id' => 4, 'uf' => 'RS'],			 			
			['title' => '2ª UAA em Jaguarão', 'court_id' => 4, 'uf' => 'RS'],			 			
			['title' => '4ª UAA em Jaguarão', 'court_id' => 4, 'uf' => 'RS'],			 			
			['title' => '4ª UAA em Santa Vitória do Palmar', 'court_id' => 4, 'uf' => 'RS'],			 			
			['title' => 'CEJUSCON da Seção Judiciária do Rio Grande do Sul', 'court_id' => 4, 'uf' => 'RS'],			 			
			['title' => '1ª Vara Federal de Porto Alegre', 'court_id' => 4, 'uf' => 'RS'],			 			
			['title' => '2ª Vara Federal de Porto Alegre', 'court_id' => 4, 'uf' => 'RS'],				 				 			
			['title' => '3ª Vara Federal de Porto Alegre', 'court_id' => 4, 'uf' => 'RS'],				 				 			
			['title' => '4ª Vara Federal de Porto Alegre', 'court_id' => 4, 'uf' => 'RS'],				 				 			
			['title' => '5ª Vara Federal de Porto Alegre', 'court_id' => 4, 'uf' => 'RS'],				 				 			
			['title' => '6ª Vara Federal de Porto Alegre', 'court_id' => 4, 'uf' => 'RS'],				 				 			
			['title' => '7ª Vara Federal de Porto Alegre', 'court_id' => 4, 'uf' => 'RS'],				 				 			
			['title' => '8ª Vara Federal de Porto Alegre', 'court_id' => 4, 'uf' => 'RS'],				 				 			
			['title' => '9ª Vara Federal de Porto Alegre', 'court_id' => 4, 'uf' => 'RS'],				 				 			
			['title' => '10ª Vara Federal de Porto Alegre', 'court_id' => 4, 'uf' => 'RS'],				 				 			
			['title' => '11ª Vara Federal de Porto Alegre', 'court_id' => 4, 'uf' => 'RS'],				 				 			
			['title' => '12ª Vara Federal de Porto Alegre', 'court_id' => 4, 'uf' => 'RS'],				 				 			
			['title' => '13ª Vara Federal de Porto Alegre', 'court_id' => 4, 'uf' => 'RS'],				 				 			
			['title' => '14ª Vara Federal de Porto Alegre', 'court_id' => 4, 'uf' => 'RS'],				 				 			
			['title' => '15ª Vara Federal de Porto Alegre', 'court_id' => 4, 'uf' => 'RS'],				 				 			
			['title' => '16ª Vara Federal de Porto Alegre', 'court_id' => 4, 'uf' => 'RS'],				 				 			
			['title' => '17ª Vara Federal de Porto Alegre', 'court_id' => 4, 'uf' => 'RS'],				 				 			
			['title' => '18ª Vara Federal de Porto Alegre', 'court_id' => 4, 'uf' => 'RS'],				 				 			
			['title' => '19ª Vara Federal de Porto Alegre', 'court_id' => 4, 'uf' => 'RS'],				 				 			
			['title' => '20ª Vara Federal de Porto Alegre', 'court_id' => 4, 'uf' => 'RS'],				 				 			
			['title' => '21ª Vara Federal de Porto Alegre', 'court_id' => 4, 'uf' => 'RS'],				 				 			
			['title' => '22ª Vara Federal de Porto Alegre', 'court_id' => 4, 'uf' => 'RS'],				 				 			
			['title' => '23ª Vara Federal de Porto Alegre', 'court_id' => 4, 'uf' => 'RS'],				 				 			
			['title' => '24ª Vara Federal de Porto Alegre', 'court_id' => 4, 'uf' => 'RS'],				 				 			
			['title' => '25ª Vara Federal de Porto Alegre', 'court_id' => 4, 'uf' => 'RS'],				 				 			
			['title' => '26ª Vara Federal de Porto Alegre', 'court_id' => 4, 'uf' => 'RS'],				 					 			
			['title' => 'CEJUSCON-PORTO ALEGRE', 'court_id' => 4, 'uf' => 'RS'],				 			
			['title' => 'Central de Execuções Penais de Porto Alegre', 'court_id' => 4, 'uf' => 'RS'],				 			
			['title' => 'SICOPREV-PORTO ALEGRE', 'court_id' => 4, 'uf' => 'RS'],				 			
			['title' => '1ª Turma Recursal do Rio Grande do Sul', 'court_id' => 4, 'uf' => 'RS'],				 			
			['title' => '2ª Turma Recursal do Rio Grande do Sul', 'court_id' => 4, 'uf' => 'RS'],				 			
			['title' => '3ª Turma Recursal do Rio Grande do Sul', 'court_id' => 4, 'uf' => 'RS'],				 			
			['title' => '4ª Turma Recursal do Rio Grande do Sul', 'court_id' => 4, 'uf' => 'RS'],				 			
			['title' => '5ª Turma Recursal do Rio Grande do Sul', 'court_id' => 4, 'uf' => 'RS'],				 			
			['title' => '1ª UAA em Camaquã', 'court_id' => 4, 'uf' => 'RS'],				 			
			['title' => '2ª UAA em Camaquã', 'court_id' => 4, 'uf' => 'RS'],				 			
			['title' => '3ª UAA em Camaquã', 'court_id' => 4, 'uf' => 'RS'],				 			
			['title' => '1ª UAA em São Jerônimo', 'court_id' => 4, 'uf' => 'RS'],				 			
			['title' => '2ª UAA em São Jerônimo', 'court_id' => 4, 'uf' => 'RS'],				 			
			['title' => '5ª UAA em São Jerônimo', 'court_id' => 4, 'uf' => 'RS'],				 			
			['title' => '4ª UAA em Torres', 'court_id' => 4, 'uf' => 'RS'],				 			
			['title' => '1ª Vara Federal de Rio Grande', 'court_id' => 4, 'uf' => 'RS'],				 			
			['title' => '2ª Vara Federal de Rio Grande', 'court_id' => 4, 'uf' => 'RS'],		 			
			['title' => '3ª Vara Federal de Rio Grande', 'court_id' => 4, 'uf' => 'RS'],			 			
			['title' => 'CEJUSCON-RIO GRANDE', 'court_id' => 4, 'uf' => 'RS'],			 			
			['title' => '2ª UAA em Santa Vitória do Palmar', 'court_id' => 4, 'uf' => 'RS'],			 			
			['title' => '3ª UAA em Santa Vitória do Palmar', 'court_id' => 4, 'uf' => 'RS'],			 			
			['title' => '1ª Vara Federal de Santa Cruz do Sul', 'court_id' => 4, 'uf' => 'RS'],			 			
			['title' => '2ª Vara Federal de Santa Cruz do Sul', 'court_id' => 4, 'uf' => 'RS'],			 			
			['title' => 'CEJUSCON-SANTA CRUZ DO SUL', 'court_id' => 4, 'uf' => 'RS'],			 			
			['title' => '1ª Vara Federal de Santa Maria', 'court_id' => 4, 'uf' => 'RS'],			 			
			['title' => '2ª Vara Federal de Santa Maria', 'court_id' => 4, 'uf' => 'RS'],			 			
			['title' => '3ª Vara Federal de Santa Maria', 'court_id' => 4, 'uf' => 'RS'],			 			
			['title' => '4ª Vara Federal de Santa Maria', 'court_id' => 4, 'uf' => 'RS'],			 			
			['title' => '10ª UAA Integrada em Gramado e Canela', 'court_id' => 4, 'uf' => 'RS'],					 			
			['title' => '5ª UAA em São Leopoldo', 'court_id' => 4, 'uf' => 'RS'],					 			
			['title' => '1ª Vara Federal de Santa Rosa', 'court_id' => 4, 'uf' => 'RS'],					 			
			['title' => '1ª Vara Federal de Santana do Livramento', 'court_id' => 4, 'uf' => 'RS'],					 			
			['title' => '2ª Vara Federal de Santana do Livramento', 'court_id' => 4, 'uf' => 'RS'],					 			
			['title' => 'CEJUSCON - SANTANA DO LIVRAMENTO', 'court_id' => 4, 'uf' => 'RS'],					 			
			['title' => '1ª Vara Federal de Santiago', 'court_id' => 4, 'uf' => 'RS'],					 			
			['title' => '1ª UAA em São Borja', 'court_id' => 4, 'uf' => 'RS'],					 			
			['title' => '1ª Vara Federal de Santo Ângelo', 'court_id' => 4, 'uf' => 'RS'],	
			['title' => '2ª Vara Federal de Santo Ângelo', 'court_id' => 4, 'uf' => 'RS'],		
			['title' => '3ª Vara Federal de Santo Ângelo', 'court_id' => 4, 'uf' => 'RS'],		
			['title' => 'CEJUSCON-SANTO ÂNGELO', 'court_id' => 4, 'uf' => 'RS'],		
			['title' => '3ª UAA em Alegrete', 'court_id' => 4, 'uf' => 'RS'],		
			['title' => '2ª UAA em Frederico Westphalen', 'court_id' => 4, 'uf' => 'RS'],				
			['title' => '3ª UAA em Itaqui', 'court_id' => 4, 'uf' => 'RS'],				
			['title' => '2ª UAA em São Luiz Gonzaga', 'court_id' => 4, 'uf' => 'RS'],				
			['title' => '3ª UAA em São Luiz Gonzaga', 'court_id' => 4, 'uf' => 'RS'],				
			['title' => '3ª UAA em São Borja', 'court_id' => 4, 'uf' => 'RS'],				
			['title' => '4ª UAA em São Borja', 'court_id' => 4, 'uf' => 'RS'],				
			['title' => '3ª Vara Federal de Santo Ângelo', 'court_id' => 4, 'uf' => 'RS'],				
			['title' => '1ª Vara Federal de Uruguaiana', 'court_id' => 4, 'uf' => 'RS'],				
			['title' => '2ª Vara Federal de Uruguaiana', 'court_id' => 4, 'uf' => 'RS'],				
			['title' => 'CEJUSCON-URUGUAIANA', 'court_id' => 4, 'uf' => 'RS'],				
			['title' => '1ª UAA em Alegrete', 'court_id' => 4, 'uf' => 'RS'],				
			['title' => '2ª UAA em Alegrete', 'court_id' => 4, 'uf' => 'RS'],				
			['title' => '1ª UAA em Itaqui', 'court_id' => 4, 'uf' => 'RS'],				
			['title' => '2ª UAA em Itaqui', 'court_id' => 4, 'uf' => 'RS']        
        ]);
						

	
			
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        //
    }
};
